### ISSUE TITLE
Typos in Slide for International Version of the Website

### ISSUE THREAD

**Issue by jitk14** [appknox/website#202]
**FMCG** is written as **FMGG** in slide for International Version of the Website.

<img width="1086" alt="screen shot 2017-11-07 at 9 27 31 pm" src="https://user-images.githubusercontent.com/1158229/32505992-856241a2-c409-11e7-9970-9af2987e7955.png">

**Comment by yashwin** [comment]
Thansk @jitk14, will update this 👍
